import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <ul className="flex space-x-4">
            <li>
              <Link href="/" title="página Principal">
                Home
              </Link>
            </li>
            <li>
              <Link href="/about" title="página sobre">
                About
              </Link>
            </li>
            <li>
              <Link href="/imc" title="página para calcular IMC">
                IMC
              </Link>
            </li>
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
